backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/uploads
public_folder: uploads
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "/src/content/home.md"
      fields:
        - label: 'IMDB Movie'
          name: "imdb_movies"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "URL", name: "url", widget: "string"}
            - { label: "Year", name: "year", widget: "string"}
            - { label: "Role", name: "role", widget: "string"}
            - { label: "Image", name: "image", widget: "image", choose_url: false}
        - label: "Portfolio images"
          name: "portfolio_images"
          widget: list
          fields:
            - { label: "Image", name: "image", widget: "image", choose_url: false, media_folder: "/public/uploads/portfolio"}
            - label: "Category"
              name: "category"
              widget: "select"
              options:
                - { label: "Propmaking", value: "propmaking" }
                - { label: "Modelmaking", value: "modelmaking"}
                - { label: "Garden design", value: "garden_design"}
                - { label: "Kobujutsu training weapons", value: "kobujutsu_training_weapons"}
                - { label: "Lino prints", value: "lino_prints"}